name: Parawee Withayasupanan, Actuary
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-cayman
show_downloads: true
title: "Parawee Withayasupanan"
repository: paraweew/paraweew.github.io
